server:
  port: 8803
spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders:
        defaultRabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings:
        input:
          destination: studyExchange
          content-type: application/json
#          binder: defaultRabbit
          #使用分组可以避免重复消费，即消息的发送者发送消息不会每一个消费者都收到
          group: TestA
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 2   #设置心跳时间（默认30s）
    lease-expiration-duration-in-seconds: 5    #设置时间间隔为5s（默认为90s）
    instance-id: receive-8803.com   #在信息列表时显示主机名
    prefer-ip-address: true    #访问路径变为IP地址