server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com #eureka服务端的实例名称，修改hosts文件之后
  client:
    register-with-eureka: false #false标识不向注册中心注册自己
    fetch-registry: false #标识自己就是注册中心，职责就是维护服务实例，并不需要去检索服务
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都依赖这个地址
#      defaultZone: http://eureka7002.com:7002/eureka/

      #使用单机----->测试hystrix，不再互相守望
       defaultZone: http://eureka7001.com:7001/eureka/