server:
  port: 9527


spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true    #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
      - id: payment_routh           #路由的id,要求唯一
#        uri: http://localhost:8001          #匹配后提供服务的路由地址
        uri: lb://payment-service     #匹配后提供服务的路由地址
        predicates:
          - Path=/payment/getPayment/**          #断言，路径相匹配的进行路由
#          - After=2022-05-11T15:44:39.918+08:00[Asia/Shanghai]     #表示在这个时间之后的才可以进行路由，若时间未到则会提示404NOT FOUND
#          - Before=2022-05-11T15:44:39.918+08:00[Asia/Shanghai]      #表示在这个时间之前的才可以路由
#          - Between=2022-05-11T15:44:39.918+08:00[Asia/Shanghai],2022-05-11T16:44:39.918+08:00[Asia/Shanghai]     #表示在这个时间之间的才可以路由
#          - Cookie=username,xxx     #表示必须要带着cookie（是一个kv键值对）才能进行路由
#          - Query=username,\d+       #表示查询必须带上username，且后面的参数必须为正数才行




      - id: payment_routh2          #路由的id
#        uri: http://localhost:8001          #匹配后提供服务的路由地址
        uri: lb://payment-service
        predicates:
          - Path=/payment/lb/**          #断言，路径相匹配的进行路由

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001//eureka
