server:
  port: 8001
spring:
  application:
    name: payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql:///course?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root



mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.test.springcloud.entities
eureka:
  client:
    #标识是否将自己注册进EurekaServer，默认为true
    register-with-eureka: true
    #是否从eurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka      #集群，同时注册进两个Eureka注册中心,http://eureka7002.com:7002/eureka
  instance:
    instance-id: payment8001  #实例名称的修改，即注册进的服务的名称修改
    prefer-ip-address: true   #IP地址的显示
